apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpha-claim
  namespace: practice
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow-storage
  volumeMode: Filesystem
